name: 'Create build info'
description: 'Create build info'
inputs:
  release-created:
    description: 'Release created'
    required: true
  release-version:
    description: 'Release version'
    required: true
  release-html-url:
    description: 'URL of created release'
    required: false
  output-file:
    description: 'Output file'
    required: true
outputs:
  version:
    description: 'Version'
    value: ${{ steps.create-build-info.outputs.version }}
runs:
  using: "composite"
  steps:
    - name: Create build info
      shell: bash
      id: create-build-info
      env:
        is_release: ${{ inputs.release-created }}
        release_html_url: ${{ inputs.release-html-url }}
        output_file: ${{ inputs.output-file }}
        release_version: ${{ inputs.release-version }}
      run: |
        tag=""
        version=""
        url=""
       
        if ! tag="$(git describe --tags --abbrev=0)"; then
          echo -e "\e[33mCould not resolve last tag, will tag as not-released\e[0m"
          tag="unreleased"
        fi
        
        echo "Tag: $tag"
        echo "Is release: $is_release"
        
        if [[ "$is_release" = 'true' ]]; then
          version="$tag"
          url=$release_html_url
        elif [[ ${{ github.event_name  }} = 'pull_request' ]] ; then
        
          # Replace all invalid characters with hyphen
          branch=$(echo ${{ github.head_ref || github.ref_name }} | sed "s/[^[:alnum:].-]/-/g")
        
          # Use format: v0.1.0-sha-0123456-pull-request-1-1-some-feature
          version="$tag-sha-${GITHUB_SHA::7}-${{ github.event_name }}-${{ github.event.number }}-build-${{ github.run_number }}-$branch"
        
          url=${{ github.event.pull_request._links.html }}
        elif [[ ${{ github.event_name }} = 'push' ]] ; then
        
          # Use format: v0.1.0-sha-0123456
          version="$tag-sha-${GITHUB_SHA::7}"
        
          url=${{ github.event.url }}
        fi
        
        echo "Version: $version"
        echo "Url: $url"
        
        echo git.commit.id.abbrev=$(git rev-parse --short=7 HEAD) > $output_file
        echo git.commit.id=$(git rev-parse HEAD) >> $output_file
        echo git.commit.user.email=$(git log -1 --pretty=format:%ae) >> $output_file
        echo git.commit.message.full=$(git log -1 --pretty=format:%B) >> $output_file
        echo git.commit.message.short=$(git log -1 --pretty=format:%s) >> $output_file
        echo git.commit.user.name=$(git log -1 --pretty=format:%an) >> $output_file
        echo git.commit.time=$(git log -1 --pretty=format:%ct --format=%cd --date=iso-strict) >> $output_file
        echo git.commit.url=$(git log -1 --pretty=format:%ct --format=%cd --date=iso-strict) >> $output_file

        echo git.tags=$tag >> $output_file
        echo git.url=$url >> $output_file
        echo git.build.version=$version > $output_file
        echo git.branch=${{ github.head_ref || github.ref_name }} >> $output_file

        {
          echo 'version<<EOF';
          echo "$version"
          echo EOF
        } >> "$GITHUB_OUTPUT"