name: 'Create build info'
description: 'Create build info'
inputs:
  is-release:
    description: 'Is release'
    required: true
  output-file:
    description: 'Output file'
    required: true
  GH_TOKEN:
    description: Github token passed from calling workflow
    required: true
outputs:
  version:
    description: 'Version'
    value: ${{ steps.create-build-info.outputs.version }}
runs:
  using: "composite"
  steps:
    - name: Create build info
      shell: bash
      id: create-build-info
      env:
        is_release: ${{ inputs.is-release }}
        is_pr: ${{ github.event_name == 'pull_request' }}
        event: ${{ format('{0}-{1}', github.event_name, github.event.number) }}
        run_number: ${{ github.run_number }}
        output_file: ${{ inputs.output-file }}
      run: |
        tag=$(git describe --tags)
        echo 123
#        if [ -z "$tag" ]; then
#          echo "No tags found in the repository."
#        else
#          echo "Latest tag: $tag"
#        fi
#
#        version=""
#
#        {
#          echo 'version<<EOF';
#          echo "$version"
#          echo EOF
#        } >> "$GITHUB_OUTPUT"
#        url=""
#        if [[  "$is_release" = 'true' ]]; then
#          version="$tag"
#        else
#          branch=$(echo ${{ github.head_ref }} | sed "s/[^[:alnum:].-]/-/g")
#          version="$tag-$event-build-$run_number-$branch-sha-${GITHUB_SHA::7}"
#          url=${{ github.event.pull_request._links.html }}
#        fi
#
#        echo git.commit.id.abbrev=$(git rev-parse --short=7 HEAD) > $output_file
#        echo git.commit.id=$(git rev-parse HEAD) >> $output_file
#        echo git.commit.user.email=$(git log -1 --pretty=format:%ae) >> $output_file
#        echo git.commit.message.full=$(git log -1 --pretty=format:%B) >> $output_file
#        echo git.commit.message.short=$(git log -1 --pretty=format:%s) >> $output_file
#        echo git.commit.user.name=$(git log -1 --pretty=format:%an) >> $output_file
#        echo git.commit.time=$(git log -1 --pretty=format:%ct --format=%cd --date=iso-strict) >> $output_file
#        echo git.commit.url=$(git log -1 --pretty=format:%ct --format=%cd --date=iso-strict) >> $output_file
#
#        echo git.tags=$tag >> $output_file
#        echo git.url=$url >> $output_file
#        echo git.build.version=$version > $output_file
#        echo git.branch=${{ github.head_ref || github.ref_name }} >> $output_file
#
