name: 'Setup docker tags'
description: 'Setup docker tags'
inputs:
  is-release:
    description: 'Is release'
    required: true
  version:
    description: 'Version'
    required: true
  suffix:
    description: 'Version'
    required: false
    default: ''
outputs:
  docker-tags:
    description: 'Docker tags'
    value: ${{ steps.setup-docker-tag.outputs.docker-tags }}

runs:
  using: "composite"
  steps:
    - name: Setup docker tags
      shell: bash
      id: setup-docker-tag
      env:
        is_release: ${{ inputs.is-release }}
        is_pr: ${{ github.event_name == 'pull_request' }}
        version: ${{ inputs.version }}
        suffix: ${{ inputs.suffix }}
      run: |
        tags=""
        if [[ "$is_release" = 'true' ]]; then
          tags="type=semver,pattern={{version}},suffix=$suffix,value=$version
                type=semver,pattern={{major}},suffix=$suffix,value=$version
                type=semver,pattern={{major}}.{{minor}},suffix=$suffix,value=$version"
        elif [[ "$is_pr" = 'true' ]]; then
          tags="type=raw,suffix=$suffix,value=$version"
        fi
        {
          echo 'docker-tags<<EOF';
          echo "$tags"
          echo EOF
        } >> "$GITHUB_OUTPUT"